#!/bin/sh
# dir=$(find $PWD -type d | grep "bachelorproef-repo" -m1)
killall firefox
dir=$(find '/Users' -type d | grep "bachelorproef-repo" -m1)
echo $dir
newdir=${dir// /"\ "}
echo $newdir
eval cd $newdir
node index.js
echo "started node server"
