#!/bin/sh
osascript -e 'quit app "Firefox"'
dir=$(find '/Users' -type d | grep "bachelorproef-repo" -m1)
echo $dir
newdir=${dir// /"\ "}
echo $newdir
eval cd $newdir
node index.js
echo "started node server"
